### ISSUE TITLE
Design  Proposals for Card Layout

### ISSUE THREAD

**Issue by LuisF06** [dannyvc95/agile-dashboard#1]
Design at least 3 proposals with different layouts for the Card element to be used in the project.

The Layout must take in consideration the following components:
type, title, description, owner, sprint, creation date, estimated time, spent time, points, status, project, priority and timeline with description, timestamp, user.

- [x] Setup React Suite in a Mock Project
- [x] Design Layout #1
- [x] Design Layout #2
- [x] Design Layout #3

**Comment by dannyvc95** [comment]
Content delivered.
